### ISSUE TITLE
.png images

### ISSUE THREAD

**Issue by w4nderlust** [storypioneers/kirby-selector#17]
If i have a .png image among the files in my page, the plugin brakes the form. I attach a visual example of the problem, the blueprint structure is the following:

```
<?php if(!defined('KIRBY')) exit ?>

title: About
pages: false
files: true
fields:
  title:
    label: Title
    type: text
  name:
    label: Name
    type:  text
  profile_image:
    label: Profile Image
    type: selector
    mode: single
    types:
      - image
```

![schermata 2015-06-22 alle 18 14 02](https://cloud.githubusercontent.com/assets/349256/8286590/b3c97ab2-190a-11e5-8f3f-522034ea0452.png)
