### ISSUE TITLE
Fatal error: Cannot access protected property SelectorField::$types

### ISSUE THREAD

**Issue by trabuccocampos** [storypioneers/kirby-selector#19]
This issue appears only on the live site and not in my local version (see screenshots below). I'm running Kirby 2.1 and as a solution have updated both Kirby and Selector to the latest versions. Still not working.

Below is the blueprint. Thanks for the help!

```
<?php if(!defined('KIRBY')) exit ?>

title: Team Member
pages: false
files: false
fields:
  title:
    label: Name
    type:  text
  text:
    label: Bio
    type:  textarea
  postimage:
    label: Main Post Image
    type:  selector
    mode:  single
    types:
      - image
  role:
    label: Role
    type:  text
    icon: video-camera
```
## Error on live site

![live_site](https://cloud.githubusercontent.com/assets/4658734/8804981/c819d3f6-2f9c-11e5-8731-7d23c850d4b4.png)
## Working well on local site

![local_site](https://cloud.githubusercontent.com/assets/4658734/8804984/c96e1988-2f9c-11e5-9d95-2f7232fb90fa.png)
