### ISSUE TITLE
Selector not working in home blueprint

### ISSUE THREAD

**Issue by aftereffectsmagic** [storypioneers/kirby-selector#40]
Hi there, 

I'm working on integrating the Selector for an image rotator that appears on the home page. I have Selector configured beautifully for other photo galleries on my event pages, that works perfectly. But when I try to add Selector to my home page, it simply does not work- the page is blank. 

Here is the working photo gallery: 

```
gallery:
        label: Gallery Images
        type:  selector
        mode:  multiple
        types:
            - image
```

But this is what is not working on the home.php blueprint: 

```
  postimage:
        label: Main Post Image
        type:  selector
        mode:  multiple
        types: 
            - image
```

When it shows the Selector, it says there are no valid image files- but I have 70 stored in my home page's content folder! Do you know why it is not working? Thanks for your help!
