### ISSUE TITLE
Not outputting full url when used on homepage

### ISSUE THREAD

**Issue by louiswalch** [storypioneers/kirby-selector#7]
Ran into a weird problem, the $page->foo()->url() doesn't return the full url on the homepage, but works fine on all other templates.

Using this code in home.php:

```
    <?php if ($page->background()): ?>
        <img src="<?php echo $page->background()->url() ?>"  />
    <?php endif ?>
```

It will just output

```
     <img src="background.jpg" />
```

**Comment by JonasDoebertin** [comment]
Let's say you have a selector field set up in your blueprint called `background`.

``` yaml
fields:
    background:
        label: Background Image
        type:  selector
        mode:  single
        types:
            - image
```

If you now just fetch the fields content in your templates/snippets, you'll get the filename of the selected file as a string (you would get a comma separated list of filenames, in case you have set the fields mode to `multiple`).

``` php
echo $page->background(); // my-file.jpg
```

If you want to have a full file object of the selected file, use the following:

``` php
$file = $page->files()->find($page->background()); // Get file object for selected file

echo $file->url(); // This would output the full file url
```

If you have a `multiple` mode field named "attachments" and want to convert all selected files to file objects, do the following:

``` php
$files = $page->files()->find(str::split($page->attachments()));

foreach($files as $file) {
    echo $file->url();
}
```

I hope that helps!

**I'll introduce a "frontend usage" part of the documentation soon.**

**Comment by louiswalch** [comment]
Jonas,

Thanks for the detailed information. I am stumped however why this is not required on other templates of the site:

**blueprints/studio.php**

```
fields:
  image:
      label: Main Image
      type: selector
      mode: single
      types:
          - image
```

**blueprints/studio.php**

```
        <?php if ($page->image()): ?>
            <img src="<?php echo $page->image()->url() ?>"  />
        <?php endif ?>
```

**outputs:**

```
<img src="http://www.foo.local/content/3-the-studio/studio.jpg"  />
```
